export const PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_OTP: "/reset-password/verify",
  RESET_PASSWORD: "/reset-password/new",
  SETTINGS: "/settings",
  SETTINGS_PASSWORD: "/settings/password",
  SETTINGS_DEACTIVATION: "/settings/deactivation",
  SETTINGS_NOTIFICATION: "/settings/notifications",
  GOOGLE_CALLBACK: "/oauth/google/callback",
  TEAMS: "/teams",
  NOTIFICATIONS: "/notifications",
  BOARDS: "/boards",
} as const;
